### ISSUE TITLE
Add encoding to additional fields

### ISSUE THREAD

**Issue by ross-spencer** [ffdev-info/jsonid#18]
It's something we have some more information about now so it can go into the additional fields and provide some extra context for users that might be helpful.

**Comment by ross-spencer** [comment]
Closed via: 83b11dbe74e12b9534f3e649740dec1ac6185403

E.g.

```yaml
---
file: samples/encoding/UTF-32LE-list.json
additional:
- '@en': data is list type
depth: 0
documentation:
- archive_team: http://fileformats.archiveteam.org/wiki/JSON
encoding: UTF-32
identifiers:
- rfc: https://datatracker.ietf.org/doc/html/rfc8259
- pronom: http://www.nationalarchives.gov.uk/PRONOM/fmt/817
- loc: https://www.loc.gov/preservation/digital/formats/fdd/fdd000381.shtml
- wikidata: https://www.wikidata.org/entity/Q2063
mime:
- application/json
name:
- '@en': JavaScript Object Notation (JSON)
---

```
