### ISSUE TITLE
Add SOPS as a YAML definition

### ISSUE THREAD

**Issue by ross-spencer** [ffdev-info/jsonid#34]
SOPS can also be represented in YAML: http://fileformats.archiveteam.org/wiki/SOPS

There are two ways to tackle this:

1. Add it as a new definition.
2. See if we can naively identify SOPS YAML via the JSON registry without changing anything <-- this would be cool!

**Comment by ross-spencer** [comment]
🎉  it worked!

```diff
diff --git a/src/jsonid/jsonid.py b/src/jsonid/jsonid.py
index eb498c3..89573ef 100644
--- a/src/jsonid/jsonid.py
+++ b/src/jsonid/jsonid.py
@@ -174,7 +174,9 @@ async def process_result(
     if doctype == registry.DOCTYPE_JSON:
         res = registry.matcher(data, encoding=encoding)
     if doctype == registry.DOCTYPE_YAML:
-        res = [registry.YAML_ONLY]
+        res = registry.matcher(data, encoding=encoding)
+        #print(a)
+        #res = [registry.YAML_ONLY]
     if doctype == registry.DOCTYPE_TOML:
         res = [registry.TOML_ONLY]
     if simple:

```

```sh
$ python jsonid.py -p integration_files/yaml/sops.yaml
```

```yaml
---
jsonid: 0.0.0
scandate: 2025-05-29T14:55:25Z
---
file: integration_files/yaml/sops.yaml
additional: ''
documentation:
- archive_team: http://fileformats.archiveteam.org/wiki/SOPS
encoding: UTF-8
identifiers:
- rfc: ''
- pronom: ''
- loc: ''
- wikidata: ''
mime: []
name:
- '@en': sops encrypted secrets file
---
```
